const translates = {
    "You receive": "You will receive",
    "This action save new server password and old key set invalid.": "Your old key will become invalid, as the WMSCrypto password will also be updated",
    "Password match. Score of strength password is 4 or 4": "Passwords match. Password complexity score is 4 or 4",
    "Password match. Score of strength password is 3 or 4": "Passwords match. Password complexity score is 3 or 4",
    "Password match. Score of strength password is 2 or 4": "Passwords match. Password complexity score is 2 or 4",
    "Password match. Score of strength password is 1 or 4": "Passwords match. Password complexity score is 1 or 4",
    "Password match. Score of strength password is 0 or 4": "Passwords match. Password complexity score is 0 or 4",
    "P == NP (optional)": "I have agreed to the conditions above without reading",
    "Make sure to write down the recovery phrase and keep it in a safe place without online access. The phrase is a master key from your wallet. It was generated on your device and you are the only person who has access to it.": "Write down the recovery phrase and keep it in a safe place without online access. The phrase is a master key from your wallet. It was generated on your device and you are the only person who has access to it.",
    "Unlock key": "Unlock the key",
    "Add input": "Add an input",
    "All fields must be present": "All fields must be filled in",
    "Inputs must be present": "Add inputs",
    "Receiver must be present": "Add receiver info",
    "Present invalid fields": "There are incorrect field entries",
    "Account for change": "Change account",
    "Output ID": "Output Index",
    "Check data": "Check your entries",
    "Offline version only for PC": "Offline version is for desktop computers only",
    "Data loading": "Loading data",
    "Please enter mnemonic from previous screen by number": "Enter the word from the recovery phrase #",
    "Check save mnemonics": "Check of the recovery phrase",
    "Generation public keys": "Public keys computation",
    "Generate key": "Key computation",
    "Create wallet": "New wallet",
    "Change wallet password": "Change password",
    "Connect wallet": "Wallet attachment",
    "Make transaction": "Build a transaction",
    "New password": "Choose a password",
    "Repeat new password": "Re-enter password",
    "Passwords match and have strong security.": "Passwords match",
    "Password length must be more 8 symbols.": "Password must be more than 8 characters long",
    "Generate mnemonics": "Recovery phrase",
    "Generate pubkeys": "Continue",
    "All pubkeys was generated successful": "All public keys are calculated",
    "Generated pubkey for": "Calculating a public key for",
    "Save mnemonics": "Save the recovery phrase",
    "Go to telegram": "Continue to Telegram",
    "Return to telegram": "Back to telegram",
    "Operation successful": "Everything worked out!",
    "Mnemonics": "Enter your recovery phrase",
    "Passphrase": "Extra words (if any)",
    "Encrypt mnemonics": "Generate QR Key",
    "Detail": "Details",
    "Fee": "Network fee",
    "Upload encrypted mnemonics": "Upload QR Key",
    "Transaction signature": "Signed transaction",
    "Download transaction data": "Signed transaction export",
    "Create from file": "Create using file",
    "Upload file with transaction data": "Upload transaction data",
    "Manual creation": "Build manually",
    "File is not json or invalid": "Invalid file format",
    "Download offline version": "Download the offline version",
    "INVALID_REQUEST": "Invalid request",
    "INVALID_UUID": "This link does not exist or expired. Get a new link from Telegram bot",
    "SORRY": "Try again later",
    "CRYPTO_FALSE": "Your browser does not support crypto-libraries. Install the latest version of Chrome, Firefox or Safari.",
    "Passwords not matched": "Passwords do not match",
    "Mnemonics invalid": "Recovery phrase is invalid. It may be unsafe to use it!",
    "Password.": "Enter your password",
    "Send transaction": "Publish the transaction",
    "Generate QR code": "QR Key generation",
    "QR code cannot be readied": "Invalid QR code",
    "Invalid anchor": "QR Key is either outdated or does not match the account",
    "Save transaction": "Save the transaction",
    "Edit transaction": "Edit the transaction",
    "ENCRYPTED_BY_ANCHOR_1": "This QR Key is not suitable for offline mode",
    "ENCRYPTED_WITHOUT_ANCHOR_1": "This QR Key is not encrypted",
    "ENCRYPTED_WITHOUT_ANCHOR_2": "and not suitable for online mode",
    "__UPDATE_QR": "Your QR key is obsolete. To maintain high-level security of your cryptoassets, we recommend updating the QR Key in \"Settings\"",
    "Invalid mnemonics": "Recovery phrase is invalid",
    "CANNOT_SCORE_PASSWORD": "Passwords match. Password complexity score is unavailable since characters other than the letters of the Latin alphabet, digits and !\"#$%&'()*+,-./:;<=>?@[]^_`{|}~' were used"
};

export default translates;