const translates = {
    "INVALID_REQUEST": "Request data for this link is invalid",
    "INVALID_UUID": "This link not exists or was expired. For make operation get new link in telegram bot",
    "SORRY": "Sorry, something wrong, try again later",
    "CRYPTO_FALSE": "Your browser cannot using secure crypto functions please use last of Chrome, Firefox or Safari",
    "SAVE_MNEMONICS": "After click on button \"Create wallet\" you see QR-key, this need for make transaction from your wallet, generated by mnemonics. Important, save this!",
    "ENCRYPTED_BY_ANCHOR_1": "Wallet encrypted using password WMS Crypto, using bot",
    "ENCRYPTED_BY_ANCHOR_2": "or create new from mnemonic using form Connect wallet",
    "ENCRYPTED_WITHOUT_ANCHOR_1": "Your QR-key not encrypted password",
    "ENCRYPTED_WITHOUT_ANCHOR_2": "and cannot using in online form",
    "Invalid anchor": "Invalid QR-key",
    "CANNOT_SCORE_PASSWORD": "Password match. Score of strength password not available, because using not english chars, not digits or not !\"#$%&'()*+,-./:;<=>?@[]^_`{|}~'"
};

export default translates;