const translates = {
    "Offline version only for PC": "Офлайн версия только для ПК",
    "ERROR": "ОШИБКА",
    "Data loading": "Загрузка данных",
    "Please enter mnemonic from previous screen by number": "Введите мнемоник с предыдущего экрана под номером",
    "Check passed": "Проверка пройдена",
    "Check save mnemonics": "Проверка записанных мнемоников",
    "Generation public keys": "Генерация публичных ключей",
    "Generate key": "Генерация ключа",
    "Next": "Далее",
    "Previous": "Назад",
    "Step": "Шаг",
    "Create password": "Создание пароля",
    "Create wallet": "Создать кошелек",
    "Change wallet password": "Изменить пароль",
    "Connect wallet": "Подключить кошелек",
    "Make transaction": "Подписать транзакцию",
    "Menu": "Меню",
    "Restart": "Очистить",
    "New password": "Придумайте пароль",
    "Repeat new password": "Повторите пароль",
    "Passwords match and have strong security.": "Пароли совпадают и не входят в топ-100 популярных паролей",
    'Password length must be 8 or more.': "Пароль не может быть короче 8 символов",
    "SAVE_MNEMONICS": "После нажатия кнопки \"Создать кошелек\" Вы увидите QR-ключ, необходимый для проведения операций с кошельком, полученным из фразы для восстановления. Обязательно сохраните его!",
    "Generate mnemonics": "Фраза для восстановления",
    "Generated mnemonics to 256-bits entropy": "Фраза для восстановления",
    "Download encrypted mnemonics": "Скачать хранилище ключей",
    "Generate pubkeys": "Продолжить",
    "All pubkeys was generated successful": "Все публичные ключи успешно сгенерированы",
    "Generated pubkey for": "Создан публичный ключ для",
    "Download pubkeys": "Скачать публичные ключи",
    "IMPORTANT!": "ВНИМАНИЕ!",
    "I've written down my recovery phrase and fully understand that password and recovery phrase are the only keys to my wallet and they cannot be recovered in case they are lost.": 'После нажатия на кнопку "Завершить создание кошелька", данное окно закроется. Пожалуйста, убедитесь, что Вы записали фразу для восстановления и сохранили картинку с QR-ключом.',
    "I understand": "Я понимаю, что однажды криптоактивы на счету этого кошелька могут стоить целое состояние, поэтому фраза для восстановления уже записана и хранится в надежном месте, а картинка с QR-ключом сохранена.",
    "Save mnemonics": "Завершить создание кошелька",
    'Save only public keys': "Только публ ключи",
    "Go to telegram": "Перейти в Telegram",
    "Return to telegram": "Вернуться в Telegram",
    "Reload in offline mode": "Перезагрузить в оффлайн режиме",
    "Operation successful": "Все получилось!",
    "Mnemonics": "Введите фразу для восстановления",
    "Passphrase": "Дополнительные слова (если есть)",
    "Encrypt mnemonics": "Создать QR-ключ",
    "Summary": "Итог",
    "Detail": "Подробнее",
    "Receiver": "Получатель",
    "Value": "К отправке",
    "Fee": "Комиссия сети",
    "Upload encrypted mnemonics": "Загрузить QR-ключ",
    "Decrypt mnemonics": "Подписать транзакцию",
    "Transaction signature": "Подписанная транзакция",
    "Download transaction data": "Скачать подписанную транзакцию",
    "Gas price": "Цена газа",
    "Gas limit": "Лимит газа",
    "Nonce": "Номер транзакции",
    "To": "Адрес",
    "Data": "Данные",
    "Create from file": "Создать из файла",
    "Upload file with transaction data": "Загрузить неподписанную транзакцию",
    "Manual creation": "Собрать вручную",
    "File is not json or invalid": "Файл не валидный json",


    "Download offline version": "Скачать офлайн версию",
    "INVALID_UUID": "Данный идентификатор не существует или просрочен",
    "SORRY": "Извините, что-то пошло не так, попробуйте позже",
    "CRYPTO_FALSE": "Ваш браузер не может использовать безопасные крипто функции, используйте последнии версии Chrome, Firefox или Safari",
    'Passwords not matched': "Пароли не совпадают",
    "Input your Passphrase": "Убрать плейсхолдер",
    "Mnemonics invalid": "Фраза для восстановления некорректна и не рекомендуется к использованию!",
    "Create mnemonics seed": "Продолжить",
    "Password.": "Введите пароль",
    "No file selected": "Файл не выбран",
    "Browse...": "Загрузить...",
    "Send transaction": "Отправить транзакцию в сеть",
    "QR-key": "QR-ключ",
    "Generate QR code": "Генерация QR кода",
    "Unlock": "Разблокировать",
    "Locked": "Заблокировано",
    "Unlocked": "Разблокировано",
    "QR code cannot be readied": "QR код не читается или отсутсвует",
    "Upload QR-key": "Загрузите QR-ключ",
    "Switch language to": "Переключить язык на",
    "Invalid password": "Неправильный пароль",
    "Invalid anchor": "Используется неправильный QR-ключ",
    "Save transaction": "Сохранить транзакцию",
    "Edit transaction": "Изменить транзакцию",
    "ENCRYPTED_BY_ANCHOR_1": "Кошелек зашифрован с помощью пароля WMS Crypto, используйте бота",
    "ENCRYPTED_BY_ANCHOR_2": "или создайте новый кошелек из мнемоника через форму прикрепления кошелька",
    "ENCRYPTED_WITHOUT_ANCHOR_1": "Ваш QR-ключ не защищен паролем",
    "ENCRYPTED_WITHOUT_ANCHOR_2": "и не может использоваться в онлайн режиме",
    "Invalid mnemonics": "Неправильные мнемоники",
    "Save accounts": "Сохранить аккаунты"
};

export default translates;
