const translates = {
    "Create wallet": "Создать кошелек",
    "Change wallet password": "Изменить пароль для кошелька",
    "Connect wallet": "Подключить кошелек",
    "Make transaction": "Сделать транзакцию",
    "Switch language to": "Переключить язык на",
    "Upload encrypted mnemonics": "Загрузить зашифрованные мнемоники",
    "Invalid password or encrypted mnemonic": "Неправильный пароль или зашифрованные мнемоники",
    "Input your Password": "Введита ваш пароль",
    "Encrypt mnemonics": "Зашифрованные мнемоники",
    "Download encrypted mnemonics": "Скачать зашифрованные мнемоники",
    "Save mnemonics": "Сохранить мнемоники",
    "Decrypt mnemonics": "Расшифровать мнемоники",
    "Mnemonics": "Мнемоники",
    "Password": "Пароль",
    "Passphrase": "Кодовая фраза",
    "Input your Passphrase": "Введите вашу кодовую фразу",
    "Create mnemonics seed": "Создать сид для мнемников",
    "Generate mnemonics": "Сгенерировать мнемоники",
    "Nonce": "Номер транзакции",
    "Gas price": "",
    "Gas limit": "",
    "Value": "Количество",
    "To": "Куда",
    "Data": "Данные",
    "Save transaction": "Сохранить транзакцию",
    "Edit transaction": "Изменить транзакцию",
    "INVALID_UUID": "Данный идентификатор не существует или просрочен",
    "Reload in offline mode": "Перезагрузить в оффлайн режиме",
    "Go to telegram": "Перейти в телеграмм",
    "SORRY": "Извините, что-то пошло не так, попробуйте позже",
    "IMPORTANT!": "ВАЖНО!",
    "I understand": "Я понимаю",
    "CRYPTO_FALSE": "Ваш браузер не может использовать безопасные крипто функции, используйте последнии версии Chrome, Firefox or Safari"
};

export default translates;