export default {
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    SET_DATA: 'SET_DATA',
    SET_ERROR: 'SET_ERROR',
    SET_RESULT: 'SET_RESULT',
    SET_APP: 'SET_APP',
    PREVIOUS_STEP: 'PREVIOUS_STEP',
    NEXT_STEP: 'NEXT_STEP',
    SET_STEP_RESULT: 'SET_STEP_RESULT',
    DROP_CURRENT_APP: 'DROP_CURRENT_APP',
    SET_GLOBAL_LOCK: 'SET_GLOBAL_LOCK',
    SET_STEPS_COUNT: 'SET_STEPS_COUNT',
    FILL_TRANSACTION_FORM: 'FILL_TRANSACTION_FORM'
}